// Generated by CoffeeScript 1.6.3
var count, promise, request;

promise = require('when');

request = require('request');

module.exports = count;

count = function(user) {
  var api, deferred, fetch, getUrl, process;
  api = 'https://rubygems.org/api/v1/owners/:user/gems.json';
  deferred = promise.defer();
  getUrl = function(user) {
    if (user == null) {
      user = '';
    }
    return api.replace(':user', user);
  };
  fetch = function() {
    var url;
    url = getUrl(user);
    return request({
      uri: url
    }, process);
  };
  process = function(err, res, body) {
    var gems;
    gems = JSON.parse(body);
    return deferred.resolve(gems.length || 0);
  };
  fetch();
  return deferred.promise;
};
